export const ENDPOINTS = [
  {
    id: 'top',
    label: 'Destacadas',
    icon: '🔬',
    description: 'Noticias científicas más destacadas del día desde España',
    accent: 'var(--accent-1)',
    endpointLabel: '/v1/news/top',
    type: 'auto',
  },
  {
    id: 'all',
    label: 'Todas las noticias',
    icon: '🧬',
    description: 'Feed completo de noticias científicas en español',
    accent: 'var(--accent-2)',
    endpointLabel: '/v1/news/all',
    type: 'auto',
  },
  {
    id: 'search',
    label: 'Buscar artículos',
    icon: '🔭',
    description: 'Busca artículos científicos por palabra clave',
    accent: 'var(--accent-3)',
    endpointLabel: '/v1/news/all?search=',
    type: 'search',
    inputPlaceholder: 'ej. cuántica, clima, inteligencia artificial…',
  },
  {
    id: 'similar',
    label: 'Artículos similares',
    icon: '⚛️',
    description: 'Encuentra artículos similares a un tema o concepto',
    accent: 'var(--accent-4)',
    endpointLabel: '/v1/news/similar',
    type: 'search',
    inputPlaceholder: 'ej. exploración espacial, CERN…',
  },
  {
    id: 'sources',
    label: 'Fuentes',
    icon: '📡',
    description: 'Explora las fuentes de publicaciones científicas',
    accent: 'var(--accent-5)',
    endpointLabel: '/v1/news/sources',
    type: 'auto',
    isSources: true,
  },
  {
    id: 'date',
    label: 'Por fecha',
    icon: '🗓️',
    description: 'Filtra noticias científicas por rango de fechas',
    accent: 'var(--accent-6)',
    endpointLabel: '/v1/news/all?published_after=&published_before=',
    type: 'date',
  },
  {
    id: 'latest',
    label: 'Últimas 24h',
    icon: '⚡',
    description: 'Noticias científicas publicadas en las últimas 24 horas',
    accent: 'var(--accent-7)',
    endpointLabel: '/v1/news/all (fecha automática)',
    type: 'auto',
  },
]

export const LANGUAGES = [
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'en', label: 'Inglés', flag: '🇬🇧' },
  { code: 'de', label: 'Alemán', flag: '🇩🇪' },
  { code: 'fr', label: 'Francés', flag: '🇫🇷' },
  { code: 'pt', label: 'Portugués', flag: '🇵🇹' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
]
