export const ENDPOINTS = [
  {
    id: 'top',
    label: 'Top Stories',
    icon: '🔬',
    description: 'Highlighted science news of the day from Germany',
    accent: 'var(--accent-1)',
    endpointLabel: '/v1/news/top',
    type: 'auto',
  },
  {
    id: 'all',
    label: 'All Science',
    icon: '🧬',
    description: 'Full science news feed from German sources',
    accent: 'var(--accent-2)',
    endpointLabel: '/v1/news/all',
    type: 'auto',
  },
  {
    id: 'search',
    label: 'Search Articles',
    icon: '🔭',
    description: 'Search German science articles by keyword',
    accent: 'var(--accent-3)',
    endpointLabel: '/v1/news/all?search=',
    type: 'search',
    inputPlaceholder: 'e.g. quantum, climate, AI…',
  },
  {
    id: 'similar',
    label: 'Similar Articles',
    icon: '⚛️',
    description: 'Find articles similar to a topic or concept',
    accent: 'var(--accent-4)',
    endpointLabel: '/v1/news/similar',
    type: 'search',
    inputPlaceholder: 'e.g. space exploration, CERN…',
  },
  {
    id: 'sources',
    label: 'News Sources',
    icon: '📡',
    description: 'Explore German science publication sources',
    accent: 'var(--accent-5)',
    endpointLabel: '/v1/news/sources',
    type: 'auto',
    isSources: true,
  },
  {
    id: 'date',
    label: 'By Date Range',
    icon: '🗓️',
    description: 'Filter science news by a custom date range',
    accent: 'var(--accent-6)',
    endpointLabel: '/v1/news/all?published_after=&published_before=',
    type: 'date',
  },
  {
    id: 'latest',
    label: 'Latest 24h',
    icon: '⚡',
    description: 'Science news published in the last 24 hours',
    accent: 'var(--accent-7)',
    endpointLabel: '/v1/news/all (auto date)',
    type: 'auto',
  },
]
